stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "$CI_REGISTRY_IMAGE"
  DOCKER_TLS_CERTDIR: ""

# =====================================================
# BUILD IMAGE
# =====================================================
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind

  rules:
    # Tags (v1.2.3)
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
      when: on_success

    # Development
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: on_success

    # Production
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success

    - when: never

  before_script:
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        DOCKER_IMAGE_TAG="$CI_COMMIT_TAG"
        DOCKERFILE_PATH="docker/production/Dockerfile"

      elif [[ "$CI_COMMIT_BRANCH" == "dev" ]]; then
        DOCKER_IMAGE_TAG="staging"
        DOCKERFILE_PATH="docker/staging/Dockerfile"

      elif [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        DOCKER_IMAGE_TAG="latest"
        DOCKERFILE_PATH="docker/production/Dockerfile"

      else
        echo "Branch or tag not allowed"
        exit 1
      fi

      export DOCKER_IMAGE_TAG
      export DOCKERFILE_PATH

      echo "================================="
      echo "Building image: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
      echo "Dockerfile: $DOCKERFILE_PATH"
      echo "================================="

    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker build --pull -f "$DOCKERFILE_PATH" -t "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" .
    - docker push "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"

# =====================================================
# PUSH TO DOCKER HUB
# =====================================================
docker-push-hub:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  needs:
    - docker-build

  rules:
    # Tags (v1.2.3)
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
      when: on_success

    # Development
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: on_success

    # Production
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success

    - when: never

  before_script:
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        TAG="$CI_COMMIT_TAG"

      elif [[ "$CI_COMMIT_BRANCH" == "dev" ]]; then
        TAG="staging"

      elif [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        TAG="latest"

      else
        echo "Invalid ref"
        exit 1
      fi

      export TAG

      echo "================================="
      echo "Pushing image with tag: $TAG"
      echo "================================="

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker pull "$DOCKER_IMAGE_NAME:$TAG"
    - docker tag "$DOCKER_IMAGE_NAME:$TAG" "$DOCKER_HUB_USER/oauth2-passport-server:$TAG"
    - docker push "$DOCKER_HUB_USER/oauth2-passport-server:$TAG"
