stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "$CI_REGISTRY_IMAGE"
  DOCKER_TLS_CERTDIR: ""
  TAG: ""

# -----------------------------
# BUILD IMAGE
# -----------------------------
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind

  before_script:
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        export DOCKER_IMAGE_TAG="$CI_COMMIT_TAG"
        export DOCKERFILE_PATH="docker/production/Dockerfile"

      elif [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        export DOCKER_IMAGE_TAG="latest"
        export DOCKERFILE_PATH="docker/production/Dockerfile"

      elif [[ "$CI_COMMIT_BRANCH" == "dev" ]]; then
        export DOCKER_IMAGE_TAG="staging"
        export DOCKERFILE_PATH="docker/staging/Dockerfile"

      else
        echo "Not a tag or configured branch. Skipping build."
        exit 0
      fi

      export TAG="$DOCKER_IMAGE_TAG"

      echo "================================="
      echo "Building image: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
      echo "Using Dockerfile: $DOCKERFILE_PATH"
      echo "================================="

    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker build --pull -f "$DOCKERFILE_PATH" -t "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" .
    - docker push "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"

  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

# -----------------------------
# PUSH TO DOCKER HUB
# -----------------------------
docker-push-hub:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  needs:
    - docker-build

  before_script:
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        export TAG="$CI_COMMIT_TAG"
      elif [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        export TAG="latest"
      elif [[ "$CI_COMMIT_BRANCH" == "dev" ]]; then
        export TAG="staging"
      else
        echo "Not a tag or configured branch. Skipping Docker Hub push."
        exit 0
      fi

      echo "Pushing image to Docker Hub with tag: $TAG"

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker pull "$DOCKER_IMAGE_NAME:$TAG"
    - docker tag "$DOCKER_IMAGE_NAME:$TAG" "$DOCKER_HUB_USER/oauth2-passport-server:$TAG"
    - docker push "$DOCKER_HUB_USER/oauth2-passport-server:$TAG"

  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
